[phases.setup]
nixPkgs = ["python312", "postgresql", "gcc"]

[phases.build]
cmds = []

[start]
cmd = "python manage.py collectstatic --noinput --clear && python manage.py migrate && gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
