[phases.setup]
nixPkgs = ["python312", "postgresql", "gcc"]

[phases.build]
cmds = []

[start]
cmd = "python manage.py collectstatic --noinput --clear && python manage.py migrate && daphne -b 0.0.0.0 -p $PORT backend.asgi:application"
