[phases.setup]
# Use python312Full so pip is available out of the box in the Nix environment
nixPkgs = ["python312Full", "postgresql"]

[phases.install]
cmds = [
	"python -m pip install --upgrade pip",
	"python -m pip install -r requirements.txt",
]

[phases.build]
cmds = [
	"python -m pip install --upgrade pip",
	"python -m pip install -r requirements.txt",
	"python manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn backend.wsgi --log-file -"
