[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.build]
cmds = [
    "mkdir -p staticfiles",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py collectstatic --noinput --clear && python manage.py migrate && gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker --log-file -"
